server:
  port: 9002

spring:
  datasource:
    driver-class-name: org.h2.Driver
    #   持久化 嵌入模式
    url: jdbc:h2:file:~/sjpa-db-min1;MODE=MySQL;
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      #  h2 访问路径上下文
      path: /h2-console
      settings:
        trace: false
        #      允许console 远程访问 默认false
        web-allow-others: true
  sql:
    init:
      schema-locations: classpath:sql/test_schema.sql #建库sql
      data-locations: classpath:sql/test_data.sql  #data.sql
      mode: always

