server:
  port: 9006

h2_db_dir: @h2db_dir@

spring:
  datasource:
    driver-class-name: org.h2.Driver
    #   持久化 嵌入模式
    url: jdbc:h2:file:${h2_db_dir}/db-qdsl-upper;MODE=MySQL;MV_STORE=true
  h2:
    console:
      enabled: true
      #  h2 访问路径上下文
      path: /h2-console
      settings:
        trace: false
        #      允许console 远程访问 默认false
        web-allow-others: true
logging:
  level:
    org.springframework.jdbc.core: DEBUG
    com.querydsl.sql: DEBUG