server:
  port: 9003

spring:
  datasource:
    #  驱动
    driver-class-name: org.h2.Driver
    #   持久化 嵌入模式
    jdbc-url: jdbc:h2:file:~/sdb-db-min;MODE=MySQL;
    # 初始化数据表
#    schema: classpath:sql/init.sql
    #  初始化数据
#    data: classpath:sql/data.sql
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      #  h2 访问路径上下文
      path: /h2-console
      settings:
        trace: false
        #      允许console 远程访问 默认false
        web-allow-others: true
  sql:
    init:
      data-locations: classpath:sql/mall_db_data.sql
      schema-locations: classpath:sql/mall_db_schema.sql
      mode: always

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

